spring.datasource.url=jdbc:postgresql://localhost:5432/tictactoe
spring.datasource.username=tictactoe_adm
spring.datasource.password=tictactoe
spring.datasource.driver-class-name=org.postgresql.Driver

jwt.secret=my-super-secret-key-that-is-at-least-32-bytes!
# 15 min:
jwt.access-ttl-ms=900000
# 7 days:
jwt.refresh-ttl-ms=604800000

spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true